// Required: npm install cheerio
import { NextResponse } from 'next/server';
import * as cheerio from 'cheerio';

// Keywords for identifying medication-related alerts
const MEDICATION_KEYWORDS = [
  'drug', 'medication', 'capsule', 'tablet', 'pharmaceutical', 'antibiotic',
  'pain reliever', 'syrup', 'injection', 'suspension', 'vaccine', 'antimalarial',
  'tapentadol', 'carisoprodol', 'amoxycillin', 'codeine', 'opioid', 'insulin'
];

const COUNTERFEIT_KEYWORDS = [
  'counterfeit', 'substandard', 'fake', 'banning', 'blacklisting', 'illegal production',
  'unregistered', 'unwholesome', 'recall', 'alert', 'adverse reaction'
];

// Keywords to exclude non-medication related alerts
const EXCLUSION_KEYWORDS = [
  'syringes', 'bioequivalence', 'scamming', 'strategic plan', 'herbal tea',
  'wholesale centre', 'antimicrobial resistance', 'miracle water', 'miracle soap',
  'executive order', 'partnership', 'ethics', 'intellectual property', 'patents',
  'destroys drugs' // This might be relevant if it's about destroying *counterfeit* drugs, but often it's general disposal.
];

// Static HTML content from NAFDAC website (as provided by user)
const NAFDAC_PRESS_RELEASES_HTML = `
| Date      | Title                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| --------- | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| 07-May-25 | [Press Briefing on Who Pre-Qualification of Afriject 0.5ml Autodisable Syringes Manufactured by Afrimedical Manufacturing & Supplies Ltd. Ibafo, Ogun State.](https://nafdac.gov.ng/press-briefing-on-who-pre-qualification-of-afriject-0-5ml-autodisable-syringes-manufactured-by-afrimedical-manufacturing-supplies-ltd-ibafo-ogun-state/ "Press Briefing on Who Pre-Qualification of Afriject 0.5ml Autodisable Syringes Manufactured by Afrimedical Manufacturing & Supplies Ltd. Ibafo, Ogun State.")                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| 10-Apr-25 | [Press Briefing on the Regulatory Framework for Bioequivalence and it’s Relevance to the Nigerian Market](https://nafdac.gov.ng/press-briefing-on-the-regulatory-framework-for-bioequivalence-and-its-relevance-to-the-nigerian-market/ "Press Briefing on the Regulatory Framework for Bioequivalence and it’s Relevance to the Nigerian Market")                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| 14-Mar-25 | [Investigation Report of Scamming of Foreign Companies Using Fake NAFDAC Documents by Mr. Ikoro Mang Ifendua: A Case of Fraud and Obtaining Funds by Impersonation as an Official of NAFDAC](https://nafdac.gov.ng/investigation-report-of-scamming-of-foreign-companies-using-fake-nafdac-documents-by-mr-ikoro-mang-ifendua-a-case-of-fraud-and-obtaining-funds-by-impersonation-as-an-official-of-nafdac/ "Investigation Report of Scamming of Foreign Companies Using Fake NAFDAC Documents by Mr. Ikoro Mang Ifendua: A Case of Fraud and Obtaining Funds by Impersonation as an Official of NAFDAC")                                                                                                                                                                                                                                                                                                                                                                                         |
| 28-Feb-25 | [Blacklisting of Aveo Pharmaceuticals and Banning of Tapentadol and Carisoprodol Combination – Tafrodol or Royal 225](https://nafdac.gov.ng/blacklisting-of-aveo-pharmaceuticals-and-banning-of-tapentadol-and-carisoprodol-combination-tafrodol-or-royal-225/ "Blacklisting of Aveo Pharmaceuticals and Banning of Tapentadol and Carisoprodol Combination – Tafrodol or Royal 225")                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| 09-Jan-25 | [The Year 2025 – NAFDAC Director General’s Strategic Plan](https://nafdac.gov.ng/the-year-2025-nafdac-director-generals-strategic-plan/ "The Year 2025 – NAFDAC Director General’s Strategic Plan")                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| 17-Dec-24 | [NAFDAC Refutes Claims of Approving Herbal Tea Promoting Smoking](https://nafdac.gov.ng/nafdac-refutes-claims-of-approving-herbal-tea-promoting-smoking/ "NAFDAC Refutes Claims of Approving Herbal Tea Promoting Smoking")                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| 13-Dec-24 | [Suspected Substandard Deekins Amoxycillin 500mg Capsule](https://nafdac.gov.ng/suspected-substandard-deekins-amoxycillin-500mg-capsule/ "Suspected Substandard Deekins Amoxycillin 500mg Capsule")                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| 26-Nov-24 | [Joint Press Briefing of NAFDAC and PCN on Coordinated Wholesale Centre in Kano- November 2024](https://nafdac.gov.ng/joint-press-briefing-of-nafdac-and-pcn-on-coordinated-wholesale-centre-in-kaduna-november-2024/ "Joint Press Briefing of NAFDAC and PCN on Coordinated Wholesale Centre in Kano- November 2024")                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| 22-Nov-24 | [Danish Embassy, Danish Veterinary and Food Agency, Partner NAFDAC to Combat Antimicrobial Resistance](https://nafdac.gov.ng/danish-embassy-danish-veterinary-and-food-agency-partner-nafdac-to-combat-antimicrobial-resistance/ "Danish Embassy, Danish Veterinary and Food Agency, Partner NAFDAC to Combat Antimicrobial Resistance")                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| 08-Sep-24 | [Illegal Production, Sale and Advertisement of Unregistered, Suspected Unwholesome Miracle Water and Other Brands of the Water, and Miracle Soap by Christ Mercy Land Delivery Ministries, Km 5 Effurun, Sapele Road, Delta State.](https://nafdac.gov.ng/illegal-production-sale-and-advertisement-of-unregistered-suspected-unwholesome-miracle-water-and-other-brands-of-the-water-and-miracle-soap-by-christ-mercy-land-delivery-ministries-km-5-effurun/ "Illegal Production, Sale and Advertisement of Unregistered, Suspected Unwholesome Miracle Water and Other Brands of the Water, and Miracle Soap by Christ Mercy Land Delivery Ministries, Km 5 Effurun, Sapele Road, Delta State.")                                                                                                                                                                                                                                                                                                 |
| 31-Aug-24 | [Emergency use authorization of the Mpox vaccine by NAFDAC: A crucial step in Nigeria's public health response](https://nafdac.gov.ng/16850-2/ "Emergency use authorization of the Mpox vaccine by NAFDAC: A crucial step in Nigeria's public health response")                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| 22-Aug-24 | [Press Briefing on WHO PQ of Swiss Pharma{Swipha}‘s Second Product Antimalarial: Sulfadoxine/Pyrimethamine Tablets {SP Combination}](https://nafdac.gov.ng/press-briefing-on-who-pq-of-swiss-pharmaswipha-s-second-product-antimalarial-sulfadoxine-pyrimethanine-tablets-sp-combination/ "Press Briefing on WHO PQ of Swiss Pharma{Swipha}‘s Second Product Antimalarial: Sulfadoxine/Pyrimethamine Tablets {SP Combination}")                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 29-Jun-24 | [NAFDAC Jubilates and Salutes Mr. President for the Bold Move to Ensure Drug and Health Security Through the Executive Order (EO)](https://nafdac.gov.ng/nafdac-jubilates-and-salutes-mr-president-for-the-bold...(77430 chars omitted)...mmerce For Import And Export Of Medicines And Health Products (CCCMHPIE)](https://nafdac.gov.ng/nigeria-china-partnership-in-local-manufacturing-of-pharmaceutical-products-and-medical-devices-regulatory-perspectives-by-professor-mojisola-christianah-adeyeye-director-general-national-agency-for/ "Nigeria-China Partnership In Local Manufacturing Of Pharmaceutical Products And Medical Devices: Regulatory Perspectives By Professor Mojisola Christianah Adeyeye Director General (NAFDAC) l Event Of China-Made Active Pharmaceutical Ingredient And Pharmaceuticals Products Of China Chamber Of Commerce For Import And Export Of Medicines And Health Products (CCCMHPIE)") |
| 28-Aug-18 | [Ethics And Intellectual Property (Patents) By Prof. Mojisola Christianah Adeyeye The Director General National Agency For Food And Drug Administration And Control (NAFDAC) At The Annual Research Fair University Of Lagos](https://nafdac.gov.ng/ethics-and-intellectual-property-patents-by-prof-mojisola-christianah-adeyeye-the-director-general-national-agency-for-food-and-drug-administration-and-control-nafdac-at-the-annual-research-fair/ "Ethics And Intellectual Property (Patents) By Prof. Mojisola Christianah Adeyeye The Director General National Agency For Food And Drug Administration And Control (NAFDAC) At The Annual Research Fair University Of Lagos")                                                                                                                                                                                                                                                                                                             |
| 18-Aug-18 | [NAFDAC Destroys Drugs And Other Unwholesome Products Worth Four Hundred And Sixty Four Million Naira Only At Gombe](https://nafdac.gov.ng/nafdac-destroys-drugs-and-other-unwholesome-products-worth-four-hundred-and-sixty-four-million-naira-only-at-gombe/ "NAFDAC Destroys Drugs And Other Unwholesome Products Worth Four Hundred And Sixty Four Million Naira Only At Gombe")                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| 25-Jul-18 | [Press Release On Antimicrobial Resistance](https://nafdac.gov.ng/press-release-on-antimicrobial-resistance/ "Press Release On Antimicrobial Resistance")                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| 06-Jul-18 | [NAFDAC Responds To The House Of Representatives’ Urge To Enforce Mobile Authentication Scheme (Mas) On Drug Products To Reduce Counterfeiting](https://nafdac.gov.ng/nafdac-responds-to-the-house-of-representatives-urge-to-enforce-mobile-authentication-scheme-mas-on-drug-products-to-reduce-counterfeiting/ "NAFDAC Responds To The House Of Representatives’ Urge To Enforce Mobile Authentication Scheme (Mas) On Drug Products To Reduce Counterfeiting")                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| 27-Jun-18 | [The Problem Of Drugs/Substance Abuse In Nigeria: A Symposium By Professor Mojisola Christianah Adeyeye Director General, NAFDAC At The University Of Benin, Benin City](https://nafdac.gov.ng/the-problem-of-drugs-substance-abuse-in-nigeria-a-symposium-by-professor-mojisola-christianah-adeyeye-director-general-nafdac-at-the-university-of-benin-benin-city/ "The Problem Of Drugs/Substance Abuse In Nigeria: A Symposium By Professor Mojisola Christianah Adeyeye Director General, NAFDAC At The University Of Benin, Benin City")                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| 27-Jun-18 | [Drug Abuse Awareness Day](https://nafdac.gov.ng/drug-abuse-awareness-day/ "Drug Abuse Awareness Day")                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| 23-Jun-18 | [Science And Science Policy For National Development](https://nafdac.gov.ng/science-and-science-policy-for-national-development/ "Science And Science Policy For National Development")                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| 23-Jun-18 | [Imperatives For National Drug Security](https://nafdac.gov.ng/imperatives-for-national-drug-security/ "Imperatives For National Drug Security")                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 22-Jun-18 | [NAFDAC Enlist The Support Of Religious Leaders And Clerics To Curb The Menace Of Drug Abuse And Misuse In The North West And North East Geo–Political Zones](https://nafdac.gov.ng/nafdac-enlist-the-support-of-religious-leaders-and-clerics-to-curb-the-menace-of-drug-abuse-and-misuse-in-the-north-west-and-north-east-geo-political-zones/ "NAFDAC Enlist The Support Of Religious Leaders And Clerics To Curb The Menace Of Drug Abuse And Misuse In The North West And North East Geo–Political Zones")                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| 22-Jun-18 | [NAFDAC Is Back At The Seaports And Borders](https://nafdac.gov.ng/nafdac-is-back-at-the-seaports-and-borders/ "NAFDAC Is Back At The Seaports And Borders")                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 12-Jun-18 | [Codeine Syrup Crisis: NAFDAC Lifts Shutdown Of Companies Implicated In Codeine Syrup Distribution And Issued Sanctions](https://nafdac.gov.ng/codeine-syrup-crisis-nafdac-lifts-shutdown-of-companies-implicated-in-codeine-syrup-distribution-and-issued-sanctions/ "Codeine Syrup Crisis: NAFDAC Lifts Shutdown Of Companies Implicated In Codeine Syrup Distribution And Issued Sanctions")                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| 07-Jun-18 | [Codeine Syrup Crisis: NAFDAC Shuts Down Peace Standard Pharmaceutical Limited, Bioraj Pharmaceutical Limited Both In Ilorin, And Emzor Pharmaceuticals Ind. Ltd, Lagos](https://nafdac.gov.ng/codeine-syrup-crisis-nafdac-shuts-down-peace-standard-pharmaceutical-limited-bioraj-pharmaceutical-limited-both-in-ilorin-and-emzor-pharmaceuticals-ind-ltd-lagos/ "Codeine Syrup Crisis: NAFDAC Shuts Down Peace Standard Pharmaceutical Limited, Bioraj Pharmaceutical Limited Both In Ilorin, And Emzor Pharmaceuticals Ind. Ltd, Lagos")                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
`;

function isMedicationRelated(title: string): boolean {
  const lowerTitle = title.toLowerCase();
  if (EXCLUSION_KEYWORDS.some(keyword => lowerTitle.includes(keyword))) {
    // Specific check for "Destroys Drugs" - could be relevant if about counterfeit/substandard
    if (lowerTitle.includes('destroys drugs') && (lowerTitle.includes('counterfeit') || lowerTitle.includes('substandard') || lowerTitle.includes('unwholesome'))) {
      // Allow if it's destroying bad drugs
    } else {
      return false; // Exclude if other exclusion keywords are present
    }
  }
  const hasMedicationKeyword = MEDICATION_KEYWORDS.some(keyword => lowerTitle.includes(keyword));
  const hasCounterfeitKeyword = COUNTERFEIT_KEYWORDS.some(keyword => lowerTitle.includes(keyword));
  
  // A NAFDAC alert can be relevant if it mentions a medication type and a problem (counterfeit, ban, etc)
  // OR if it specifically mentions a problem like "counterfeit" "substandard" etc. for a product that is implicitly a medication
  // OR if it's about a specific drug that's often problematic (e.g. codeine)
  return hasMedicationKeyword || hasCounterfeitKeyword;
}

// Helper function to parse DD-Mon-YY date strings
function parseDate(dateStr: string): Date {
  const [day, monthStr, yearSuffix] = dateStr.split('-');
  const months: { [key: string]: number } = {
    Jan: 0, Feb: 1, Mar: 2, Apr: 3, May: 4, Jun: 5,
    Jul: 6, Aug: 7, Sep: 8, Oct: 9, Nov: 10, Dec: 11
  };
  const year = parseInt(yearSuffix, 10) + 2000; // Assuming 21st century
  return new Date(year, months[monthStr], parseInt(day, 10));
}

export async function GET() {
  try {
    const $ = cheerio.load(NAFDAC_PRESS_RELEASES_HTML);
    const allAlerts: any[] = [];

    // The HTML is a markdown table, so we look for table rows.
    // Each press release is in a row, starting from the third row (index 2) after headers.
    const rows = $('body').text().split('\n').map(row => row.trim()).filter(row => row.startsWith('| ') && row.length > 2);
    
    // Skip header rows
    for (let i = 2; i < rows.length; i++) {
      const columns = rows[i].split('|').map(col => col.trim()).filter(Boolean);
      if (columns.length === 2) {
        const dateString = columns[0];
        const titleAndLinkMatch = columns[1].match(/\[(.*?)\]\((.*?)\)/); // Matches [Title](link)

        if (titleAndLinkMatch && titleAndLinkMatch.length === 3) {
          const title = titleAndLinkMatch[1];
          const link = titleAndLinkMatch[2];
          
          if (isMedicationRelated(title)) {
            allAlerts.push({
              title: title.replace(/\"/g, '"'), // Clean up escaped quotes if any
              link: link,
              date: dateString,
              parsedDate: parseDate(dateString), // For sorting
              summary: title.replace(/\"/g, '"').substring(0, 150) + (title.length > 150 ? "..." : "") // Use title as summary
            });
          }
        }
      }
    }

    // Sort alerts by date, most recent first
    allAlerts.sort((a, b) => b.parsedDate.getTime() - a.parsedDate.getTime());

    // Get the top 3
    const alerts = allAlerts.slice(0, 3).map(alert => ({
        title: alert.title,
        link: alert.link,
        date: alert.date,
        summary: alert.summary
    }));

    return NextResponse.json({ alerts });
  } catch (error: any) {
    console.error("Error processing NAFDAC alerts:", error);
    return NextResponse.json({ error: 'Failed to process NAFDAC alerts', details: error?.message || String(error) }, { status: 500 });
  }
}
